**Author: Rameshwar L Kumawat, Georgia Tech**

# *1. Creating an Array in NumPy*

In [ ]:
#! Importing numpy from colab

import numpy as np

In [ ]:
#! Creating a simple 1D array: vector

np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
#! Creating 2D array: matrix

np.array([(1,2,3,4,5), (6,7,8,9,10)])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#! Creatin an array from a list

num_list = [1,2,3,4,5]
np.array(num_list)
print(np.array(num_list))

[1 2 3 4 5]


## 1.1 Generating an Array

NumPy offers various options to generate an array depending on particular need, such as

*   Generating An Identity Array
*   Generating Zero Array of a Given Size
*   Generating Ones Array of a Given Size
*   Generating An Array in a Given Range
*   Generating Zero Array with Random Values






In [ ]:
#! Generating An Identity Array

identity_array = np.identity(4)
print(identity_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#! Generating An Identity Matrix of 1s

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#! We Can Multiply with Any Constant

np.eye(4) * 5

array([[5., 0., 0., 0.],
       [0., 5., 0., 0.],
       [0., 0., 5., 0.],
       [0., 0., 0., 5.]])

In [ ]:
#! Generating Zero Array of a Given Size
#! 1D Zero Array
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
#! Generating Zero Array of a Given Size
#! 2D Zero Array: Pass the tuple of rowa and columns' number
#! np.zeros((row, columns))

np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
#! Generating Ones Array of a Given Size
#! 1D One Array

np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
#! Generating Ones Array of a Given Size
#! 2D One Array: Pass the tuple of rowa and columns' number
#! np.zeros((row, columns))

np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])