**Deep Learning with PyTorch**

PyTorch is a Python-based computing package. It is serving two broad purposes.

1. A replacement for NumPy (NP) to use the power of graphic processing units (GPUs) and other acceloerators.
2. An automatic differentiation library that is useful to implement neural networks (NN).

Goal of this notebook.

- Understand PyTorch’ Tensor library and NNs at high-level.
- Train a small NN to classify images.

**Note**

Install Torch and TorchVision packages.

In [1]:
%matplotlib inline

**Tensors**

Tensors are known as a specialized data structure that are closely similar to arrays and matrices.

In PyTorch computing package, we use tensors to encode the I/Ps and O/Ps of a model, as well as the model's parameters.

Tensors are similar to NP's ndarrays (N-dimensional arrays), except that tensors can run on GPUs to accelerate computation.

**ndarray:** An ndarry is a multidimensional container of items of the same type and size.

In [2]:
import torch
import numpy as np

**Tensor Initialization**

It can initiate in several ways.

Example

**Directly from Data:** It can be created directly from data and the data type is automatically inferred.

In [3]:
data = [[2,3], [4,5]]
x_data = torch.tensor(data)

**From a NumPy array:** It can be created from NumPy array.

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**From another tensor:** The new tensor retains the properties (datatype, shape) of the augment tesnor, unless explicity overridden.

In [5]:
x_ones = torch.ones_like(x_data) # Retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # Overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9147, 0.9657],
        [0.2390, 0.9336]]) 



**With Random or Constant Values:** Shape is a tuple of tensor dimensions. In the function belwo, it determins the dimensionality of the O/P tensor.

In [6]:
shape = (4,5,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.5127, 0.1700, 0.8246, 0.7209, 0.1559],
        [0.1611, 0.6174, 0.9436, 0.7843, 0.9657],
        [0.3057, 0.8423, 0.6854, 0.8967, 0.9992],
        [0.6004, 0.0155, 0.4525, 0.6010, 0.5830]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]) 



**Tensor Attributes:** Tensor attributes describe their datatype, shape, and the device on which they are stored.

In [7]:
tensor = torch.rand(4,5)
print(f"Datatype of Tensor: {tensor.dtype}")
print(f"Shape of Tensor: {tensor.shape}")
print(f"Devie tensor is stored on: {tensor.device}")

Datatype of Tensor: torch.float32
Shape of Tensor: torch.Size([4, 5])
Devie tensor is stored on: cpu


**Tensor Operations:** Over 100 tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random sampling, and more are comprehensively described on PyTorch webpag.

In [8]:
#! one can move tensor to GPU if availabe
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


**Standard NumPy-Like Indexing and Slicing**

In [13]:
tensor = torch.ones(5,5)
tensor[:,2] = 0
print(tensor)

tensor([[1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.]])


**Multiplying Tensors**

In [15]:
#! This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")

#! Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.]])


**Matrix Multiplication Between Two Tensors**

In [17]:
#! This computes the matrix multiplication between two tensors
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")

#! Aternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]]) 

tensor @ tensor.T 
 tensor([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]])
